require ('thermostat')
t = Thermostat:new(nil, 2,77)
print("Test: ")
t:test()
print("Ideal temp 70")
t:print_ideal_temp()
t:setIdealTemp(77)

print("Ideal temp 77")
print(t:getIdealTemp())

print("state should be off")
print(t:getState())
print(t:getTemp())
t:tick()
print("off wait")
print(t:getState())
t:setTemp(80)
t:tick()
print("off wait")
print(t:getState())
t:setTemp(60)
t:tick()
print("on wait")
print(t:getState())
print("json object")
print(t:toJSON())
